# Generated by Django 2.0.3 on 2018-03-29 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sem_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.Semester'),
        ),
    ]
