# Generated by Django 2.0.3 on 2018-03-29 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_subject_sem_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sem_name',
            new_name='semester',
        ),
    ]
