# Generated by Django 2.0.3 on 2018-03-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180329_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='sem_name',
            new_name='semester',
        ),
    ]
