# Generated by Django 2.0.3 on 2018-04-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_semester_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='optional',
            field=models.NullBooleanField(),
        ),
    ]
